title: Ali G in the town!
author: Ali G
email: alig@weststainesmassif.com
description: > # this means to ignore newlines until "baseurl:"
  Yo! Booyaakaashaa! Ali G here. From West Side!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
